# -*- coding: utf-8 -*-
"""Aula_1_2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJeO3N7TRhtx5WEL5VxHIiSDovRavCfo

#PRIMEIRA AULA DE PYTHON

##1 - Comando PRINT()
O comando print é um comando de saída, ou seja, a partir dele que conseguimos imprimir informações na tela.<br>


Este comando é uma método de impressão, portanto, **sempre** que o usarmos, temos que colocar os (). 

---

```
print()
```
---
Dentro dos () podemos colocar qualquer tipo de informação que desejamos informar ao usuário.

###1. Fazer um programa que escreve na tela Olá Mundo!
"""



"""###2. Concatenando informações """

# Texto e números

# Texto com booleano

# Textos longos, com mais de uma linha

# Imprimir a mensagem 
#     "Professor, você é muito legal"
# Mas o muito deve ser repetido 25 vezes.

"""##2 - Tipos de variáveis
O Python é uma linguagem de programação dinamicamente tipada, ou seja, não precisamos declarar o tipo da variável na sua criação e podemos alterar o tipo de dado a qualquer momento. Veja o código abaixo:

---
```
a = 10
a = "Texto"
a = True
a = ['Batatinha', 'Frita', 1, 2, 3, True]
a = {'usuario': "Joao",
     'idade': 40,
     'filhos': True,
     }
```
---
O sinal de = significa **recebe**, portanto, a linha ***a = 10*** deve ser lida como ***a recebe 10***

###1. Número Inteiro
Importante: O Python **não** utiliza separador entre as partes inteiras, ou seja, não vamos escrever 1.000 ou 1,000. Podemos usar o _ para fazer a separação entre as casas de milhar.

---
```
numero_inteiro = 1000000
numero_inteiro = 1_000_000
```
---
Nos dois casos apresentados acima, temos o número 1 milhão.
"""

# Decalarar a Variável Inteira

# Imprimir as variáveis na tela (usar .format)

"""###2. Números Reais
Importante: O Python utiliza o . como separador entre a parte inteira e a parte decimal do número.

---
```
pi = 3.14
```
---
"""

# Declarar a Variável Real

# Imprimir as variáveis na tela (usar .format)

"""###3. Texto e Comentário
Para escrever um texto, podemos utilizar tando aspas simples (' ') quanto aspas duplas (" ").

---
```
texto_1 = 'Batatinha'
texto_2 = " Frita"
print(texto_1 + texto_2)
```
---
"""

# Declarar a Variável tipo String

# Declarar a Variável tipo Comentário

# Imprimir as variáveis na tela (usar .format)

# Declarar duas variáveis tipo String

# Imprimir as frase em um print()

"""###4. Lógico ou Booleano
Este tipo de dado está relacionado com **Verdadeiro** ou **Falso**. Confira o código abaixo:

---
```
logico = True
```
---
"""

# Declarar a Variável tipo Boolean

# Imprimir as variáveis na tela (usar .format)

"""###Lista
Variável que armazena conjunto de informações. As listas **sempre** devem obedecer o mesmo jeito de ser definidas.

---
```
lista = ["Batatinha","Frita",1 ,2, 3, True]
```
---
"""

# Declarar a Variável tipo Lista

# Imprimir as variáveis na tela (usar .format)

"""###Dicionário
Variável que armazena conjunto de informações. Os dicionários funcionam num sistema denominado de chave: valor. Cada chave terá um valor.
O valor pode ser qualquer coisa. 

---
```
dic = {"username": 'jamelao.free',
        "idade": 40,
        "filho": True
      }
```
---
"""

# Declarar a Variável tipo Dicionário


# Imprimir as variáveis na tela (usar .format)

"""##3 - Entrada de dados com INPUT()
O método de entrada de dados **imput()** é utilizado quando queremos que o usuário digite alguma informação. 

Como um método, este comando também precisa ser utilizado com (). Entro dos () devemos colocar o texto que aparecerá ao usuário.<br>

#### ***Este texto deverá instruir o usuário a digitar o que o programa espera como entrada.***

Este método **sempre** recebe a informação como um texto e, às vezes, para ulitizar esta informação, precisamos converte-la para outro tipo de dado (inteiro ou float). Vamos ver o código abaixo para entender melhor:

---
```
numero = input("Entre com um número: ")
print(type(numero))
numero = int(numero)
print(type(numero))
```
---
Neste código podemos verificar que primeiro a informação foi inserida como um texto quando precisamos utilizá-la, fizemos a conversão para um número inteiro.

###Texto
"""

# Declarar variável nome

# Imprimir na tela: "Olá Fulano, tudo bem?"

"""###Número Inteiro"""

# Declarar variável número


# Imprimir na tela: "O número digitado foi "NÚMERO""

"""###Número Real

"""

# Declarar variável número

# Imprimir na tela: "O número digitado foi "NÚMERO""

"""##4 - Operadores Aritméticos
São aqueles operadores matemáticos utilizados para fazer as contas mas, em Python, temos alguns especiais.

###Adição (+)
Use o campo abaixo para fazer um programa que realize a soma de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a soma da primeira variável com a segunda variável

# Imprimir na tela

"""###Subtração (-)
Use o campo abaixo para fazer um programa que realize a subtração de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a subtração da primeira variável com a segunda variável

# Imprimir na tela

"""###Multiplicação (*)
Use o campo abaixo para fazer um programa que realize a multiplicação de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a multiplicação da primeira variável com a segunda variável

# Imprimir na tela

"""###Divisão (/)
Use o campo abaixo para fazer um programa que realize a divisão de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a divisão da primeira variável com a segunda variável

# Imprimir na tela

"""###Módulo (%) -> resto de uma divisão
Use o campo abaixo para fazer um programa que mostre o resto da divisão de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer o módulo da primeira variável com a segunda variável

# Imprimir na tela

"""###Exponenciação (**)
Use o campo abaixo para fazer um programa que faça a exponenciação de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a exponenciação da primeira variável com a segunda variável

# Imprimir na tela

"""###Divisão Inteira (//)
Use o campo abaixo para fazer um programa que faça a divisão inteira de dois números inteiros.<br>
✅***Usando os métodos input() e print()***
"""

# Declarar a primeira variável:

# Declarar a segunda variável:

# Fazer a divisão inteira da primeira variável com a segunda variável

# Imprimir na tela

"""##5 - Exercícios

###Fazer programa que converte a velocidade de m/s para km/h. Dado: velocidade(m/s) = velocidade(km/h) * 3.6
"""

# Declaração da variável velocidade

# Conversão da velocidade

# Imprimir na tela a velocidade convertida

"""###Fazer um programa em que o usuário digita o raio de um circunferência e o programa imprime na tela o seu comprimento."""

# Importação da biblioteca math

# Declaração da variável

# Calcular o comprimento

# Imprimir na tela

"""###Fazer um programa em qeue o usuário entra com um número e o programa imprime na tela seu antecessor e seu sucessor."""

# Declaração da variável

# Calcular o antecessor

# Calcular o sucessor

# Imprimir na tela

"""###Fazer um programa em que o usuário entra com o ano de seu nascimento e o programa imprime na tela ssua idade."""

# Declaração da variável

# Calcular aniversário

# Imprimir na tela o aniversário